name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3 
        with: 
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew bulid
      - name: Build apk
        uses: actions/upload-artifact@v2.1.4
        with:
          name: privateMessenger
          path: app/build/outputs/apk/debug/app-debug.apk
